apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: web-secrets
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: doppler-secret-store
    refreshInterval: "3m"
    target:
        name: web-secrets
    data:
        - secretKey: SENDGRID_API_TOKEN
          remoteRef:
            key: SENDGRID_API_TOKEN
